name: Flutter Build

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'

      - name: Fix Android Embedding
        run: |
          mkdir -p android/app/src/main/kotlin/com/example/victory_app
          echo 'package com.example.victory_app
          import io.flutter.embedding.android.FlutterActivity
          class MainActivity: FlutterActivity() {}' > android/app/src/main/kotlin/com/example/victory_app/MainActivity.kt

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle --release

      - name: Build Web
        run: flutter build web --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: victory-app-builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            build/web/
