name: Flutter Build

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'

      - name: Fix Android Embedding
        run: |
          # Создаем директорию для MainActivity
          mkdir -p android/app/src/main/kotlin/com/example/victory_app
          
          # Создаем MainActivity.kt
          echo 'package com.example.victory_app
          import io.flutter.embedding.android.FlutterActivity
          class MainActivity: FlutterActivity() {}' > android/app/src/main/kotlin/com/example/victory_app/MainActivity.kt
          
          # Обновляем minSdkVersion
          sed -i 's/minSdkVersion .*/minSdkVersion 21/' android/app/build.gradle
          
          # Добавляем интернет-разрешение
          sed -i '/<manifest /a <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml

      - name: Install Dependencies
        run: |
          flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-sound-null-safety

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: victory-app-apk
          path: build/app/outputs/flutter-apk/app-release.apk
